config/routes.rb
Rails.application.routes.draw do

  concern :range_searchable, BlacklightRangeLimit::Routes::RangeSearchable.new
  mount Blacklight::Engine => '/'
  mount BlacklightAdvancedSearch::Engine => '/'

  root to: "catalog#index"
  concern :searchable, Blacklight::Routes::Searchable.new
  get "/pages/:page" => "pages#show"
  resource :catalog, only: [:index], as: 'catalog', path: '/catalog', controller: 'catalog' do
    concerns :searchable
    concerns :range_searchable

  end

  get '/catalog/:id/admin' => 'catalog#admin', as: 'admin_catalog'

  devise_for :users
  concern :exportable, Blacklight::Routes::Exportable.new

  resources :solr_documents, only: [:show], path: '/catalog', controller: 'catalog' do
    concerns :exportable
  end

  resources :bookmarks do
    concerns :exportable

    collection do
      delete 'clear'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
mount Geoblacklight::Engine => 'geoblacklight'
        concern :gbl_exportable, Geoblacklight::Routes::Exportable.new
        resources :solr_documents, only: [:show], path: '/catalog', controller: 'catalog' do
          concerns :gbl_exportable
        end
        concern :gbl_wms, Geoblacklight::Routes::Wms.new
        namespace :wms do
          concerns :gbl_wms
        end
        concern :gbl_downloadable, Geoblacklight::Routes::Downloadable.new
        namespace :download do
          concerns :gbl_downloadable
        end
        resources :download, only: [:show]
end

app/controllers/catalog_controller.rb
# -*- encoding : utf-8 -*-
require 'blacklight/catalog'

class CatalogController < ApplicationController
  include BlacklightAdvancedSearch::Controller
  include BlacklightRangeLimit::ControllerOverride
  include Blacklight::Catalog

  configure_blacklight do |config|


    # Advanced config values
    # default advanced config values
    config.advanced_search ||= Blacklight::OpenStructWithHashAccess.new
    config.advanced_search[:url_key] ||= 'advanced'
    config.advanced_search[:query_parser] ||= 'edismax'
    config.advanced_search[:form_solr_parameters] ||= {}
    config.advanced_search[:form_solr_parameters]['facet.field'] ||= %W[uw_provenance_advanced_search_s uw_creator_advanced_search_sm]
    config.advanced_search[:form_solr_parameters]['facet.query'] ||= ''
    config.advanced_search[:form_solr_parameters]['facet.limit'] ||= -1
    config.advanced_search[:form_solr_parameters]['facet.sort'] ||= 'index'

    # Map views
    config.add_results_collection_tool(:view_type_group)
    config.view.mapview.partials = [:index]
    config.view['split'].title = "List view"
    config.view['mapview'].title = "Map view"

    # Ensures that JSON representations of Solr Documents can be retrieved using
    # the path /catalog/:id/raw
    # Please see https://github.com/projectblacklight/blacklight/pull/2006/
    config.raw_endpoint.enabled = true

    ## Default parameters to send to solr for all search-like requests. See also SolrHelper#solr_search_params
    ## @see https://lucene.apache.org/solr/guide/6_6/common-query-parameters.html
    ## @see https://lucene.apache.org/solr/guide/6_6/the-dismax-query-parser.html#TheDisMaxQueryParser-Theq.altParameter
    config.default_solr_params = {
      start: 0,
      'q.alt' => '*:*',
      'bf' => ['if(exists(uw_deprioritize_item_b),0,100)^0.5']
    }

    ## Default rows returned from Solr
    ## @see https://lucene.apache.org/solr/guide/6_6/common-query-parameters.html
    config.default_per_page = 20

    ## Default parameters to send on single-document requests to Solr. These settings are the Blackligt defaults (see SolrHelper#solr_doc_params) or
    ## parameters included in the Blacklight-jetty document requestHandler.
    #
    config.default_document_solr_params = {
     :qt => 'document',
     :q => '{!raw f=layer_slug_s v=$id}'
    }



    # solr field configuration for search results/index views
    # config.index.show_link = 'title_display'
    # config.index.record_display_type = 'format'

    config.index.title_field = Settings.FIELDS.TITLE

    # solr field configuration for document/show views

    config.show.display_type_field = 'format'
    config.show.partials << 'show_default_viewer_container'
    config.show.partials << 'show_default_attribute_table'
    config.show.partials << 'show_default_viewer_information'

    ##
    # Configure the index document presenter.
    config.index.document_presenter_class = Geoblacklight::DocumentPresenter

    # solr fields that will be treated as facets by the blacklight application
    #   The ordering of the field names is the order of the display
    #
    # Setting a limit will trigger Blacklight's 'more' facet values link.
    # * If left unset, then all facet values returned by solr will be displayed.
    # * If set to an integer, then "f.somefield.facet.limit" will be added to
    # solr request, with actual solr request being +1 your configured limit --
    # you configure the number of items you actually want _displayed_ in a page.
    # * If set to 'true', then no additional parameters will be sent to solr,
    # but any 'sniffed' request limit parameters will be used for paging, with
    # paging at requested limit -1. Can sniff from facet.limit or
    # f.specific_field.facet.limit solr request params. This 'true' config
    # can be used if you set limits in :default_solr_params, or as defaults
    # on the solr side in the request handler itself. Request handler defaults
    # sniffing requires solr requests to be made with "echoParams=all", for
    # app code to actually have it echo'd back to see it.
    #
    # :show may be set to false if you don't want the facet to be drawn in the
    # facet bar
    # config.add_facet_field 'format', :label => 'Format'
    # config.add_facet_field 'pub_date', :label => 'Publication Year', :single => true
    # config.add_facet_field 'subject_topic_facet', :label => 'Topic', :limit => 20
    # config.add_facet_field 'language_facet', :label => 'Language', :limit => true
    # config.add_facet_field 'lc_1letter_facet', :label => 'Call Number'
    # config.add_facet_field 'subject_geo_facet', :label => 'Region'
    # config.add_facet_field 'solr_bbox', :fq => "solr_bbox:IsWithin(-88,26,-79,36)", :label => 'Spatial'

    # config.add_facet_field 'example_pivot_field', :label => 'Pivot Field', :pivot => ['format', 'language_facet']

    # config.add_facet_field 'example_query_facet_field', :label => 'Publish Date', :query => {
    #    :years_5 => { :label => 'within 5 Years', :fq => "pub_date:[#{Time.now.year - 5 } TO *]" },
    #    :years_10 => { :label => 'within 10 Years', :fq => "pub_date:[#{Time.now.year - 10 } TO *]" },
    #    :years_25 => { :label => 'within 25 Years', :fq => "pub_date:[#{Time.now.year - 25 } TO *]" }
    # }

    config.add_facet_field Settings.FIELDS.PART_OF, :label => 'Collection', :limit => 5, collapse: false
    config.add_facet_field Settings.FIELDS.CREATOR, :label => 'Created By', :limit => 5, collapse: false
    config.add_facet_field Settings.FIELDS.PROVENANCE, label: 'Held By', limit: 5, collapse: false

    # Advanced search - Work around for facet.limit bug
    config.add_facet_field 'uw_creator_advanced_search_sm', :label => 'Created By', show: false
    config.add_facet_field 'uw_provenance_advanced_search_s', label: 'Held By', show: false

    config.add_facet_field 'time_period', :label => 'Time Period', :query => {
      'Future' => { :label => 'Future', :fq => "solr_year_i:[#{Time.now.year + 1} TO 3000]"},
      '2015-present' => { :label => '2015-present', :fq => "solr_year_i:[2015 TO #{Time.now.year}]"},
      '2010-2014' => { :label => '2010-2014', :fq => "solr_year_i:[2010 TO 2014]" },
      '2005-2009' => { :label => '2005-2009', :fq => "solr_year_i:[2005 TO 2009]" },
      '2000-2004' => { :label => '2000-2004', :fq => "solr_year_i:[2000 TO 2004]" },
      '1990-1999' => { :label => '1990-1999', :fq => "solr_year_i:[1990 TO 1999]" },
      '1980-1989' => { :label => '1980-1989', :fq => "solr_year_i:[1980 TO 1989]" },
      '1970-1979' => { :label => '1970-1979', :fq => "solr_year_i:[1970 TO 1979]" },
      '1960-1969' => { :label => '1960-1969', :fq => "solr_year_i:[1960 TO 1969]" },
      '1950-1959' => { :label => '1950-1959', :fq => "solr_year_i:[1950 TO 1959]" },
      '1940-1949' => { :label => '1940-1949', :fq => "solr_year_i:[1940 TO 1949]" },
      '1930-1939' => { :label => '1930-1939', :fq => "solr_year_i:[1930 TO 1939]" },
      '1920-1929' => { :label => '1920-1929', :fq => "solr_year_i:[1920 TO 1929]" },
      '1910-1919' => { :label => '1910-1919', :fq => "solr_year_i:[1910 TO 1919]" },
      '1900-1909' => { :label => '1900-1909', :fq => "solr_year_i:[1900 TO 1909]" },
      '1800s' => { :label => '1800s', :fq => "solr_year_i:[1800 TO 1899]" }
    }, collapse: true
    config.add_facet_field Settings.FIELDS.YEAR, label: 'Year', limit: 10, collapse: false, all: 'Any year', range: {
      assumed_boundaries: [1100, 3000]
    }
    config.add_facet_field Settings.FIELDS.SUBJECT, :label => 'Subject', :limit => 5, collapse: true
    config.add_facet_field Settings.FIELDS.PUBLISHER, :label => 'Publisher', :limit => 8
    #config.add_facet_field Settings.FIELDS.RIGHTS, label: 'Access', limit: 8, partial: "icon_facet"
    config.add_facet_field Settings.FIELDS.GEOM_TYPE, label: 'Data type', limit: 8, partial: "icon_facet"
    config.add_facet_field Settings.FIELDS.FILE_FORMAT, :label => 'Format', :limit => 5

    # Have BL send all facet field names to Solr, which has been the default
    # previously. Simply remove these lines if you'd rather use Solr request
    # handler defaults, or have no facets.
    config.add_facet_fields_to_solr_request!

    # solr fields to be displayed in the index (search results) view
    #   The ordering of the field names is the order of the display
    # config.add_index_field 'title_display', :label => 'Title:'
    # config.add_index_field 'title_vern_display', :label => 'Title:'
    # config.add_index_field 'author_display', :label => 'Author:'
    # config.add_index_field 'author_vern_display', :label => 'Author:'
    # config.add_index_field 'format', :label => 'Format:'
    # config.add_index_field 'language_facet', :label => 'Language:'
    # config.add_index_field 'published_display', :label => 'Published:'
    # config.add_index_field 'published_vern_display', :label => 'Published:'
    # config.add_index_field 'lc_callnum_display', :label => 'Call number:'

    # config.add_index_field 'dc_title_t', :label => 'Display Name:'
    # config.add_index_field Settings.FIELDS.PROVENANCE, :label => 'Institution:'
    # config.add_index_field Settings.FIELDS.RIGHTS, :label => 'Access:'
    # # config.add_index_field 'Area', :label => 'Area:'
    # config.add_index_field Settings.FIELDS.SUBJECT, :label => 'Keywords:'
    config.add_index_field Settings.FIELDS.TEMPORAL
    config.add_index_field Settings.FIELDS.CREATOR
    config.add_index_field Settings.FIELDS.DESCRIPTION, helper_method: :snippit
    config.add_index_field Settings.FIELDS.PUBLISHER



    # solr fields to be displayed in the show (single result) view
    #  The ordering of the field names is the order of the display
    #
    # item_prop: [String] property given to span with Schema.org item property
    # link_to_search: [Boolean] that can be passed to link to a facet search
    # helper_method: [Symbol] method that can be used to render the value

app/views/catalog/_citation.html.erb
<div class="modal-header">
  <button type="button" class="ajax-modal-close close" data-dismiss="modal" aria-hidden="true">×</button>

  <h3 class="modal-title"><%= t('blacklight.tools.citation') %></h3>
</div>
<div class="modal-body">
  <% @documents.each do |document| %>
    <% case document["dc_type_sm"].present? && document["dc_type_sm"].join(",").downcase %>
    <% when "collection" %>
      <p>
        <% if document["dc_title_s"].present? %>
          <i><%= document["dc_title_s"] %></i>.
        <% end %>

        <% if document["dc_publisher_sm"].present? %>
          <%= document["dc_publisher_sm"].join(', ') %>.
        <% end %>
      Available from:
      <%= url_for(:only_path => false).split("/citation")[0] %>.
      </p>
    <% else %>
      <p>
        <% if document["dc_creator_sm"].present? %>
          <%= document["dc_creator_sm"].join(', ') %>.
        <% else %>
           [creator not found],
        <% end %>

        <% if document["solr_year_i"].present? %>
          (<%= citation_solr_year_i(document["solr_year_i"]) %>).
        <% elsif document["dct_temporal_sm"].present? %>
          (<%= document["dct_temporal_sm"][0] %>).
        <% else %>
          (n.d.).
        <%- end %>

        <% if document["dc_title_s"].present? %>
          <i><%= document["dc_title_s"] %></i>.
        <% end %>

        <% if document["dc_publisher_sm"].present? %>
          <%= document["dc_publisher_sm"].join(', ') %>.
        <% end %>

        <% if document["dct_provenance_s"] == "UW-Madison Robinson Map Library" %>
            <%= url_for(:only_path => false).split("/citation")[0] %>
        <% else %>
            <% if document.references.url.present? %>
                <%= document.references.url.endpoint %>
            <% end %>
        <% end %>
    </p>
      </p>
    <% end %>


  <% end %>
</div>

app/views/catalog/_dataset_notice.html.erb
<% document ||= @document %>
<div class="alert alert-danger alert-dismissible dataset-notice" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span>
  </button>

  <%= document[Settings.FIELDS.NOTICE] %>
</div>

app/views/catalog/_document_mapview.html.erb
<div class='row'>
  <div id="documents" class="documents-list col-md-6 map-view">
    <%= render documents, :as => :document %>
  </div>
  <%= content_tag :div, '', id: 'map', class: 'col-md-6', data: { map: 'index', 'catalog-path'=> search_catalog_path , 'map-bbox' => params[:bbox], basemap: geoblacklight_basemap, leaflet_options: leaflet_options } %>
</div>

app/views/catalog/_document_split.html.erb
<div class="row">
  <div id="documents" class="documents-list col-md-12">
    <%= render documents, :as => :document %>
  </div>
</div>

app/views/catalog/_header_icons.html.erb
<%= geoblacklight_icon(document[Settings.FIELDS.GEOM_TYPE]) %>
<%= geoblacklight_icon(document[Settings.FIELDS.RIGHTS]) %>

app/views/catalog/_home_text.html.erb
<div class='container-fluid'>
  <div class='row'>
    <div class='col-lg-5 order-1'>

      <div class='row text-center'>

        <div class='col-sm col-12 order-1'>         
          <div class='card mx-auto'>
          <h4 class='card-header facet-field-heading' >Browse All</h4>
             <%= link_to image_tag("maplayers-index-page.svg",{:class => "uw-home-icon", :alt => "Browse All"}), "/?search_field=all_fields&q=" %>
          </div>     
        </div>
        <div class='col-sm col-12 order-2'>         
          <div class='card mx-auto'>
          <h4 class='card-header facet-field-heading'>WI State Agency Layers</h4>
            <%= link_to image_tag("wisconsin.svg",{:class => "uw-home-icon", :alt => "Statewide Layers"}), "?f%5Bdct_isPartOf_sm%5D%5B%5D=Wisconsin+State+Agencies&q=&search_field=all_fields" %>
          </div>
        </div>
      </div>
      <div class='row text-center'>
        <div class='col-sm col-12 order-3'>
          
          <div class='card mx-auto'>
          <h4 class='card-header facet-field-heading'>Coastal Layers</h4>
            <%= link_to image_tag("waves.svg",{:class => "uw-home-icon", :alt => "Coastal Layers"}), "/?f%5Bdct_isPartOf_sm%5D%5B%5D=Coastal" %>
          </div>     
        </div>
        <div class='col-sm col-12 order-4'>
          
          <!-- <div class='card uw-icon-container mx-auto'> -->
          <div class='card mx-auto'> 
          <h3 class='card-header facet-field-heading'>Aerial Imagery</h3>
            <%= link_to image_tag("airphoto.svg",{:class => "uw-home-icon", :alt => "Aerial Imagery"}), "/?f%5Bdct_isPartOf_sm%5D%5B%5D=Aerial+Imagery" %>
          </div>
        </div>
      </div>
      <div class='row text-left'>
        <div class='col-md order-1 mb-3'> 
            <p><em>GeoData@Wisconsin</em> is an online geoportal that provides discovery and access to Wisconsin geospatial data, imagery, and scanned maps. To learn more about the all-new GeoData application, check out our <a href="/pages/about">about</a> and <a href="/pages/help">help</a> pages</a>!</p>
        </div>
    </div>
      <div class='row'>
        <div class='col-sm order-1'>
        <h4 class='sr-only'>Creator</h4>
           <%= render_facet_partials [:dc_creator_sm], {class:'active'} %>
        </div>
        <div class='col-sm order-2'>
        <h4 class='sr-only'>Held By</h4>
          <%= render_facet_partials [:dct_provenance_s] %>
        </div>
      </div>
    </div>
    <div id="wrapper-map" class='col-lg-7 order-2'>
      <%= content_tag :div, '', id: 'map', data: { map: 'home', 'catalog-path'=> search_catalog_path , 'map-bbox' => params[:bbox], basemap: geoblacklight_basemap, leaflet_options: leaflet_options } %>
    </div>
  </div>
</div>

app/views/catalog/_index_mapview_default.html.erb
<% # header bar for doc items in index view -%>
<%= content_tag :div, class: 'documentHeader row', data: { layer_id: document.id, bbox: document.bounding_box_as_wsen } do %>
  <div class='status-icons'>
    <%= render partial: 'header_icons', locals: { document: document } %>
  </div>
  <h3 class="index_title col-sm-9s cosl-lg-10 text-span">
    <span class='caret-toggle'></span>
    <% counter = document_counter_with_offset(document_counter) %>
    <span class="document-counter">
      <%= t('blacklight.search.documents.counter', :counter => counter) if counter %>
    </span>
    <%= link_to_document document, counter: counter, title: document[blacklight_config.index.title_field] %>
  </h3>

  <div class='col-md-12 more-info-area'>
    <div class='collapse' data-collapse-target="<%= document.id %>">
      <small>
        <%= geoblacklight_present(:index_fields_display, document) %>
      </small>
    </div>
  </div>
<% end %>

app/views/catalog/_index_split_default.html.erb
<% # header bar for doc items in index view -%>
<%= content_tag :div, class: 'documentHeader row', data: { layer_id: document.id, bbox: document.bounding_box_as_wsen } do %>
<div class="list-icon col">
  <div class='media'>
    <%- if document.sidecar.image.attached? %>
      <%- if document.sidecar.image.variable? %>
        <%= image_tag document.sidecar.image.variant(resize: "200"), {class: 'img-fluid'} %>
      <%- else %>
        <%= image_tag document.sidecar.image, {class: 'mr-3'} %>
      <%- end %>
    <%- else %>
        <%= geoblacklight_icon(document[Settings.FIELDS.GEOM_TYPE]) %>
    <%- end %>
  </div>
</div>
<div class="list-title col">
    <p class="mb-1">
        <% counter = document_counter_with_offset(document_counter) %>
        <span class="document-counter">
            <%= t('blacklight.search.documents.counter', :counter => counter) if counter %>
        </span>
        <span><%= link_to_document document, counter: counter, title: document[blacklight_config.index.title_field] %> <%= render partial: 'header_icons', locals: { document: document } %></span></p>
    <p><%= geoblacklight_present(:index_fields_display, document) %></p>
</div>
<% end %>

app/views/catalog/_search_form.html.erb
<%= form_tag search_action_url, method: :get, class: 'search-query-form', role: 'search' do %>
  <%= render_hash_as_hidden_fields(search_state.params_for_search.except(:q, :search_field, :qt, :page, :utf8)) %>
  <% if search_fields.length > 1 %>
    <label for="search_field" class="sr-only"><%= t('blacklight.search.form.search_field.label') %></label>
  <% end %>
  <div class="input-group">
    <% if search_fields.length > 1 %>
        <%= select_tag(:search_field,
                       options_for_select(search_fields, h(params[:search_field])),
                       title: t('blacklight.search.form.search_field.title'),
                       id: "search_field",
                       class: "custom-select search-field") %>
    <% elsif search_fields.length == 1 %>
      <%= hidden_field_tag :search_field, search_fields.first.last %>
    <% end %>

    <label for="q" class="sr-only"><%= t('blacklight.search.form.search.label') %></label>
    <%= text_field_tag :q, params[:q], placeholder: t('blacklight.search.form.search.placeholder'), class: "search-q q form-control", id: "q", autofocus: presenter.autofocus?, data: { autocomplete_enabled: presenter.autocomplete_enabled?, autocomplete_path: search_action_path(action: :suggest) }  %>

    <span class="input-group-append">
      <button type="submit" class="btn btn-primary search-btn" id="search">
        <span class="submit-search-text"><%= t('blacklight.search.form.submit') %></span>
        <%= blacklight_icon :search %>
      </button>    
    </span><%= link_to 'Advanced', blacklight_advanced_search_engine.advanced_search_path(search_state.to_h), class: 'advanced_search btn btn-link'%>
  </div>
<% end %>

app/views/catalog/_show.html.erb
<% doc_presenter = show_presenter(document) %>
<%# default partial to display solr document fields in catalog show view -%>

<dl class="row dl-invert document-metadata">
  <% doc_presenter.fields_to_render.each do |field_name, field| -%>
    <dt class="blacklight-<%= field_name.parameterize %> col-md-3"><%= render_document_show_field_label document, field: field_name %></dt>
    <dd class="blacklight-<%= field_name.parameterize %> col-md-9"><%= doc_presenter.field_value field %></dd>
  <% end -%>
</dl>

<%= render 'dataset_notice' if render_dataset_notice?(document) %>

app/views/catalog/_web_services_default.html.erb
<% document ||= @document %>

<div class='form-group web-services-form'>
  <h2 class='h5' for='<%= reference.type%>_webservice'>
    <%= "#{formatted_name_reference(reference.type)}" %>
  </h2>
  <a class='text' id='<%= reference.type%>_webservice' href='<%= reference.endpoint %>' target='_blank'> <%= reference.endpoint %>
  </a>
</div>

app/views/catalog/admin.html.haml
%h3=@document[blacklight_config.index.title_field]

%table.table.table-borderless.table-sm
  %thead
    %tr
      %th Provenance
      %th Indexed

  %tbody
    %tr
      %td= @document._source['dct_provenance_s']
      %td= DateTime.parse(@document._source['timestamp']).strftime('%D %r')
%hr

%h3 SolrDocument
%div.solr-document
  != ap @document.to_h

%br
%h3 Item Viewer
%table.table
  %thead
    %tr
      %th Protocol
      %th Endpoint
  %tbody
    %tr
      %td= @document.viewer_protocol
      %td= link_to(@document.viewer_endpoint, @document.viewer_endpoint)

- if @document.respond_to?(:sidecar)
  %h3 Thumbnail
  %table.table
    %thead
      %tr
        %th Display
        %th Attached
        %th State
        %th Last Transition
    %tbody
      %tr
        - if @document.sidecar.image.attached?
          %td
            %div.media
              %span.mr-3= image_tag @document.sidecar.image
        - else
          %td
            %div.media
              %span.icon.square.mr-3
                =geoblacklight_icon(@document[Settings.FIELDS.GEOM_TYPE])

        %td= @document.sidecar.image.attached?
        %td= @document.sidecar.image_state.current_state
        %td
          - if @document.sidecar.image_state.last_transition
            = @document.sidecar.image_state.last_transition.metadata

%h3 URIs
%table.table.responsive
  %thead
    %tr
      %th State
      %th Key
      %th Value

  %tbody
    - @document.uris.each do |uri|
      %tr
        %td= uri.state_machine.current_state
        %td= uri.uri_key
        %td
          = link_to(uri.uri_value, uri.uri_value)

- if @document.respond_to?(:access_links)
  %h3 Access Links
  %table.table.responsive
    %thead
      %tr
        %th University
        %th Access Link
    %tbody
      - b1g_access_links(@document).each do |key,value|
        %tr
          %td=key
          %td
            %a{href:value}=value

:javascript
  new Readmore( '.solr-document', { maxHeight: 40 } );